spring:
  application:
    name: login-service
  datasource:
    url: jdbc:h2:mem:usuariosdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
jwt:
  secret: cNBYx5W7aP7Q7q6r2X3UoHd6x4o7t+fPgE7nVjJc3sY=
  expiration: 3600000